version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    rebase-strategy: "disabled"
    schedule:
      interval: "monthly"
    groups:
      github-actions-update:
        patterns:
          - "*"
