apiVersion: v1
kind: Service
metadata:
  name: {{ include "csi-driver-availability-monitor.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "csi-driver-availability-monitor.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: metrics
      protocol: TCP
      port: {{ .Values.service.metrics.port }}
      targetPort: 8080
    - name: receiver
      protocol: TCP
      port: 8082
      targetPort: 8082
  selector:
    {{- include "csi-driver-availability-monitor.selectorLabels" . | nindent 4 }}
