name: "Lint Charts"

on:
  pull_request:
    paths:
      - "charts/**"
      - "ct.yaml"

jobs:
  lint:
    runs-on: "ubuntu-20.04"

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Setup Go"
        uses: actions/setup-go@v3
        with:
          go-version: "1.19"

      - name: "Set up chart-testing"
        uses: helm/chart-testing-action@v2.3.1

      - name: "Run chart-testing (list-changed)"
        id: list-changed
        run: |
          changed=$(ct list-changed --config ct.yaml)
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: "Run chart-testing (lint)"
        run: ct lint --config ct.yaml
