name: "Lint Charts"

on:
  pull_request:
    paths:
      - "charts/**"
      - "ct.yaml"

jobs:
  lint:
    runs-on: "ubuntu-20.04"

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Setup Go"
        uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"

      - name: "Set up chart-testing"
        uses: helm/chart-testing-action@v2.4.0

      - name: "Run chart-testing (lint)"
        run: ct lint --config ct.yaml
