name: "Main"
on:
  pull_request:
  push:
    branches:
      - "main"

permissions:
  contents: read
  id-token: write

jobs:
  build:
    name: "build"
    runs-on: "ubuntu-22.04"
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup-go
        with:
          go-version-file: "go.mod"
          takumi-guard-bot-id: ${{ vars.TAKUMI_GUARD_BOT_ID }}
      - run: make check-uncommitted
      - run: make lint
      - run: make test
      - run: make docker-build
