name: "Main"
on:
  pull_request:
  push:
    branches:
      - "main"

permissions:
  contents: read

jobs:
  build:
    name: "build"
    runs-on: "ubuntu-22.04"
    steps:
      - uses: actions/checkout@v7.0.0
      - uses: actions/setup-go@v6.4.0
        with:
          go-version-file: "go.mod"
      - run: make check-uncommitted
      - run: make lint
      - run: make test
      - run: make docker-build
